### ISSUE TITLE
Hash in file name?

### ISSUE THREAD

**Issue by frederikhors** [omeid/go-resources#14]
Is there a way to serve the same files with hash in their name for aggressive caching?

**Comment by omeid** [comment]
Yes, it is possible. The ideal way to go about this would be to have a `FileSystemStripHash` type that wraps the original `http.FileSystem` generated by `go-resources` and call it with the stripped name, here is a quick sketch:

```go
type FileSystemStripHash struct {
	http.FileSystem
}

func (fs *FileSystemStripHash) Open (name string) (http.File, error) {
	let strip = StripHashFromName(name)

	return fs.FileSystem.Open(name)
}


// use it as you please:
var HashIgnoringFS = &FileSystemStripHash{GeneratedFS}
```

For more control, you can always use the library to create your own command line, and you can set the names as you please when you add them with `Add/AddFile` methods.

**Comment by omeid** [comment]
If that doesn't solve your problem, please feel free to reopen the issue.
