### ISSUE TITLE
Forcing path to / results in weird defaults

### ISSUE THREAD

**Issue by lionello** [omeid/go-resources#15]
Running `resources` with relative paths like `../logo.png` results in assets that have a weird name like `"/../logo.png"` (parent of the root?). 

I'd find it more predictable if the default asset names are identical to the paths used during generation. Perhaps an new option `--root` could be added to keep the current behavior?

https://github.com/omeid/go-resources/blob/46f4269d8abdc8829f45595f162f6bd0b7ee2a16/resources.go#L299

**Comment by omeid** [comment]
Hello @lionello,

Sorry for late reply. In the context of _web_ `/../logo.png` means parent of the current documents' directory and is used fairly often I am afraid.

A `--root` option is an acceptable solution, any reason you can't run `resources` from the a `base` that you no longer need relative paths?

Hope this helps.

**Comment by omeid** [comment]
Closing due to lack of response.
