### ISSUE TITLE
Inconsistency between live directory and embedded fs paths

### ISSUE THREAD

**Issue by bowerscd** [omeid/go-resources#18]
At the moment, it's impossible to have a mirrored live directory and an embedded filesystem.

Assume that you have the following directory layout:

```
/
| ---- resources/ 
          |--------- res_manager.go
          |--------- embedded.go
          |--------- non-embed.go
          |--------- web/
                      |----- mycss.css
                      |----- myimage.png
          |--------- snd/
                      |----- mysnd.ogg
                      |----- othersnd.ogg
```

generating the embedded file system (`embedded.go`) via

```bash
$GOPATH/bin/resources -tags embed -declare -package resources -output embedded.go web/* snd/*
```

will result in the following path-mapping:

```
/web/mycss.css
/web/myimage.png
/snd/mysnd.ogg
/snd/othersnd.ogg   
```

However, serving the live directory (`non-embed.go`) via:

```go
   live.Dir("./")
```

will result in the following path-mapping:

```
web/mycss.css
web/myimage.css
snd/mysnd.ogg
snd/othersnd.ogg
```

(needless to say, using `/` as the path will map the entire filesystem, outside of a chroot, which is bad.)

This, as a result, causes a disconnect between common code, as the mapping must be _exact_ for code to actually find the file. The `-trim` argument, also fails to do this, because it is hard coded in the template. 

Tangentially related: #15

**Comment by omeid** [comment]
Thanks for the PR. We will follow the discussion there.

**Comment by omeid** [comment]
Thanks for the PR and opening the issue Trevor.

The `live.Dir` behaviour comes from golang's `http.Dir` so I would rather keep things consistent with that as per your PR.

At the same time I am reluctant to change the generated code because the way people use the binary to generate the resource is often not versioned and  I prefer we didn't break any code.

Can you please give me a sample code of where this unfortunate difference becomes a problem? And how did you got the paths?

Thank you!

**Comment by bowerscd** [comment]
I'm the one that actually that opened the issue - I see Trevor was the one that submitted the fix, however.

[Here's](https://gitlab.com/the-tito-foundation/tito/-/tree/master/resources) an example in an actual (for fun) project. The function is loadEmbed.

In this code, resources are identified by a URI, the schema for resources created by go-resources would be `embed://<file/path>`.

When served by live.Dir, this works just fine. You trim the `embed://` and look up the relevant path. For embedded, there's now a second level of code that needs to be maintained, because you have to trim `embed:/` vs `embed://`. The argument here is the code should be identical between the live hosted version (on the provision that this is typically used for quicker dev-cycles, or instances where the environment cannot compile all the embedded resources [that's what the above code does; gitlab ci/cd runs out of memory trying to compile the resources]).

The fix I idealized was just making the leading `/` be respected by `-trim` argument, not breaking the default behavior, or some other argument, perhaps `-abs-trim`, preserving back compat?

**Comment by omeid** [comment]
So would you be happy with a solution that works with both `/paht/to/file` and `path/to/file`?

**Comment by bowerscd** [comment]
As long as I can make the generated code's paths match the paths served from `live.Dir`, I'll be happy, even if it means I need to make a code change, or change how I'm calling `go-resources`

**Comment by omeid** [comment]
For new projects there is the official embed package, so it is not worth it to introduce breaking changes to this project now. Closing this as unfortunate.
