### ISSUE TITLE
How to add files from subfolder to resource asset?

### ISSUE THREAD

**Issue by pavel-odintsov** [omeid/go-resources#3]
Hello!

I'm trying to add files from subfolder to asset:
```bash
ls -al resources/mongodb/repolist.static 
-rw-r--r-- 1 root root 73 Jan 14 11:18 resources/mongodb/repolist.static
```

But it's not working with following call:
```bash
resources -output="public_resources.go" -var="StaticResources" resources/*
```

Actually "mongodb" folder itself have added correctly:
```bash
cat public_resources.go |grep mongodb -C 5
			}, "/resources/mongodb": File{
				data: []byte{},
				fi: FileInfo{
					name:    "mongodb",
					size:    4096,
					modTime: time.Unix(1452847762, 1452847762787760103),
					isDir:   true,
				},

```

But nested file "repolist.static" haven't added :(

Do you have any plans to implement this feature?

**Comment by omeid** [comment]
Sorry for the lack of proper documentation but command line tool `resources` uses [filepath.Glob](https://golang.org/pkg/path/filepath/#Glob) fromwhich has the same syntax pattern as [filepath.Match](https://golang.org/pkg/path/filepath/#Match).

Which means, you can't glob more than one directory level, but you can pass as many patterns to `resource` command as you wish, so you can do 

`

so if you're using bash for example, you can just do  the following command should work for your usecase:

`resources -output="public_resources.go" -var="StaticResources" resources/*

**Comment by pavel-odintsov** [comment]
Thanks! Will try this way. It's also works for me.

**Comment by stroborobo** [comment]
For the record: using `$(find $mydir)` as an argument works as well and you're not relying on some shell's features. (Since I just tripped over this, too. :) )
