### ISSUE TITLE
Can't readdir files in "/"

### ISSUE THREAD

**Issue by pstibrany** [omeid/go-resources#4]
Right now following code returns error (where `fs` is generated http.FileSystem implementation), and doesn't return list of files.

```go
	d, err := fs.Open("/")
	if err != nil {
		return nil, err
	}

	files, err := d.Readdir(0)
	if err != nil {
		return nil, err
	}
```

Here is a patch that fixes that:

```patch
diff --git a/resources.go b/resources.go
index daeccd7..4591958 100644
--- a/resources.go
+++ b/resources.go
@@ -188,6 +188,10 @@ func (f *File) Close() error {
 }
 
 func (f *File) Readdir(count int) ([]os.FileInfo, error) {
+  if f.fi.isDir {
+    return f.fi.files, nil
+  }
+
   return nil, os.ErrNotExist
 }
 
@@ -226,10 +230,6 @@ func (f *FileInfo) IsDir() bool {
        return f.isDir
 }
 
-func (f *FileInfo) Readdir(count int) ([]os.FileInfo, error) {
-       return f.files, nil
-}
-
 func (f *FileInfo) Sys() interface{} {
        return f.sys
 }
```

**Comment by omeid** [comment]
The implementation of this will need to take into account the number of files requested (the `count`) and if there has been any previous calls (the count of already listed files).

I will look into this shortly.

**Comment by pstibrany** [comment]
Oh, that's right. I always use it with 0, so my fix works for my case :)

**Comment by omeid** [comment]
I am closing this in favour of #6. Please subscribe to the said issue if you're still interested in a solution to this. Thanks again for bringing this to my attention.
