### ISSUE TITLE
Readdir() returns invalid result – one file many times

### ISSUE THREAD

**Issue by pstibrany** [omeid/go-resources#5]
FileSystem has a map of File structures:
```go
type FileSystem struct {
	files map[string]File
}
```

When iterating over this map in FileSystem.Open function, each File value from map is copied into `file` variable:

```go
		for path, file := range fs.files {
			if strings.HasPrefix(path, name) {
				s, _ := file.Stat()
				files = append(files, s)
			}
		}
```

When `file.Stat()` is called, what actually happens is `(&file).Stat()` (because `Stat()` is only defined on `*File`, not `File`), and `Stat()` returns

```go
func (f *File) Stat() (os.FileInfo, error) {
  return &f.fi, nil
}
```

That is, address of `fi` field of `file` variable from for loop in our case. This is then added to the result.

Subsequent iterations overwrite `file` variable, and thus also its `fi` field, but `file.Stat()` still returns the same address -- one that was used in previous iterations as well.

End result is that `files` slice contains same result several times.

```
0: *main.FileInfo 0xc82009c380
1: *main.FileInfo 0xc82009c380
2: *main.FileInfo 0xc82009c380
```

We can fix that by doing

```go
		for path, file := range fs.files {
			if strings.HasPrefix(path, name) {
				f := file // copy to new variable, that will end up in the `files`
				s, _ := f.Stat()
				files = append(files, s)
			}
		}
```

**Comment by omeid** [comment]
Thanks for reporting this. 
If the problem persists please feel free to reopen this issue.
